List<Map<String, dynamic>> fakeData = [
  {
    'catagory': 'car',
    'subCatagory': 'subCatagory',
    'currency': 'SAR',
    'amount': 230.00,
    'note': 'note',
    'type': 'TransactionType.moneyOut',
    'wallet': 'wallet',
    'fromWallet': 'fromWallet',
    'toWallet': 'None',
    'date': '2024-03-28 21:09:49.382752'
  },
  {
    "catagory": "food",
    "subCatagory": "Fruits",
    "currency": "USD",
    "amount": 40.55,
    "note": "Weekly fruit shopping",
    "type": "TransactionType.moneyOut",
    "wallet": "Checking Account",
    "fromWallet": "Checking Account",
    "toWallet": "None",
    "date": "2024-03-28T08:30:00.000Z"
  },
  {
    'catagory': 'hygene',
    'subCatagory': 'subCatagory',
    'currency': 'SAR',
    'amount': 100.40,
    'note': 'note',
    'type': 'TransactionType.moneyOut',
    'wallet': 'wallet',
    'fromWallet': 'fromWallet',
    'toWallet': 'None',
    'date': '2024-03-28 21:09:49.382752'
  },
  {
    "catagory": "random",
    "subCatagory": "socks",
    "currency": "USD",
    "amount": 20.55,
    "note": "Weekly fruit shopping",
    "type": "TransactionType.moneyOut",
    "wallet": "Checking Account",
    "fromWallet": "Checking Account",
    "toWallet": "None",
    "date": "2024-03-28T08:30:00.000Z"
  },
  {
    'catagory': 'food',
    'subCatagory': '',
    'currency': 'SAR',
    'amount': 13.50,
    'note': 'note',
    'type': 'TransactionType.moneyOut',
    'wallet': 'wallet',
    'fromWallet': 'fromWallet',
    'toWallet': 'None',
    'date': '2024-03-28 21:09:49.382752'
  },
  {
    "catagory": "gas",
    "subCatagory": "Fruits",
    "currency": "SAR",
    "amount": 20.55,
    "note": "Weekly fruit shopping",
    "type": "TransactionType.moneyOut",
    "wallet": "Checking Account",
    "fromWallet": "Checking Account",
    "toWallet": "None",
    "date": "2024-03-28T08:30:00.000Z"
  },
  {
    'catagory': 'loan',
    'subCatagory': 'from sis',
    'currency': 'USD',
    'amount': 50.00,
    'note': 'note',
    'type': 'TransactionType.moneyIn',
    'wallet': 'wallet',
    'fromWallet': 'fromWallet',
    'toWallet': 'None',
    'date': '2024-03-13 21:09:49.382752'
  },
  {
    "catagory": "food",
    "subCatagory": "",
    "currency": "SAR",
    "amount": 20.55,
    "note": "Weekly fruit shopping",
    "type": "TransactionType.moneyOut",
    "wallet": "Checking Account",
    "fromWallet": "Checking Account",
    "toWallet": "None",
    "date": "2024-03-28T08:30:00.000Z"
  },
  {
    'catagory': 'random',
    'subCatagory': 'subCatagory',
    'currency': 'SAR',
    'amount': 10.40,
    'note': 'note',
    'type': 'TransactionType.moneyIn',
    'wallet': 'wallet',
    'fromWallet': 'fromWallet',
    'toWallet': 'None',
    'date': '2024-03-28 21:09:49.382752'
  },
  {
    "catagory": "gas",
    "subCatagory": "",
    "currency": "USD",
    "amount": 20.55,
    "note": "Weekly fruit shopping",
    "type": "TransactionType.moneyOut",
    "wallet": "Checking Account",
    "fromWallet": "Checking Account",
    "toWallet": "None",
    "date": "2024-03-28T08:30:00.000Z"
  },
  {
    'catagory': 'car',
    'subCatagory': 'radiator',
    'currency': 'SAR',
    'amount': 10.40,
    'note': 'note',
    'type': 'TransactionType.moneyOut',
    'wallet': 'wallet',
    'fromWallet': 'fromWallet',
    'toWallet': 'None',
    'date': '2024-03-28 21:09:49.382752'
  },
  {
    "catagory": "food",
    "subCatagory": "food",
    "currency": "SAR",
    "amount": 20.55,
    "note": "Weekly fruit shopping",
    "type": "TransactionType.moneyOut",
    "wallet": "Checking Account",
    "fromWallet": "Checking Account",
    "toWallet": "None",
    "date": "2024-04-28T08:30:00.000Z"
  },
  {
    "catagory": "loan",
    "subCatagory": "food",
    "currency": "SAR",
    "amount": 400.00,
    "note": "Weekly fruit shopping",
    "type": "TransactionType.moneyIn",
    "wallet": "Checking Account",
    "fromWallet": "Checking Account",
    "toWallet": "None",
    "date": "2024-03-28T08:30:00.000Z"
  },
];
